// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import "@vue/runtime-core"

export {}

declare module "@vue/runtime-core" {
  export interface GlobalComponents {
    AppGallery: typeof import("./src/components/AppGallery.vue")["default"]
    ISiGithub: typeof import("~icons/simple-icons/github")["default"]
    ISiMaildotru: typeof import("~icons/simple-icons/maildotru")["default"]
    ISiTelegram: typeof import("~icons/simple-icons/telegram")["default"]
    RouterLink: typeof import("vue-router")["RouterLink"]
    RouterView: typeof import("vue-router")["RouterView"]
  }
}
